

const EventData = [
    {
      id: 1,
      image: require('../assets/bg2.jpg'),
      title: 'AYALOLO RELOADED',
      content: 'We are thrilled to announce the launch of our latest innovation, the Skaihub Smartwatch. Designed with cutting-edge technology and a sleek, modern aesthetic, this smartwatch is the perfect companion for the active and tech-savvy individual.',
      creator: 'By Skaihub | May 15, 2024  |',
      views: 50,
      stars: 4,
      description: '',
    },
    {
      id: 2,
      image: require('../assets/bg9.jpg'),
      title: 'ABENA SIKA PREMO',
      content: 'Skaihub is excited to announce the upcoming annual developer conference, where industry experts and tech enthusiasts will gather to explore the latest advancements in software development, cloud computing, and artificial intelligence.',
      creator: 'By Skaihub | June 1, 2024  |',
      views: 50,
      stars: 4,
      description: '',
    },
    {
      id: 3,
      image: require('../assets/bg4.jpg'),
      title: 'HYPERS AWARD & DINNER NIGHT',
      content: 'We are proud to introduce our brand-new mobile app, designed to provide our users with a seamless and intuitive experience. With enhanced features, improved performance, and a sleek user interface, the Skaihub app is the ultimate tool for staying connected and productive on the go.',
      creator: 'By Skaihub | July 1, 2024  |',
      views: 50,
      stars: 4,
      description: '',
    },
    {
      id: 4,
      image: require('../assets/bg8.jpg'),
      title: 'GHANA FASHION SHOW\'24',
      content: 'Skaihub is committed to fostering the next generation of tech innovators. We are excited to launch our scholarship program, which will provide financial assistance and mentorship opportunities to talented individuals pursuing careers in software development and computer science.',
      creator: 'By Skaihub | August 1, 2024  |',
      views: 50,
      stars: 4,
      description: '',
    },
    {
      id: 5,
      image: require('../assets/bg1.jpeg'),
      title: 'MAN ON STREAK',
      content: 'Skaihub is committed to fostering the next generation of tech innovators. We are excited to launch our scholarship program, which will provide financial assistance and mentorship opportunities to talented individuals pursuing careers in software development and computer science.',
      creator: 'By Skaihub | August 10, 2024  |',
      views: 50,
      stars: 4,
      description: '',
    },
    {
      id: 6,
      image: require('../assets/bg5.jpg'),
      title: 'ADIZA THE MAD WOMAN',
      content: 'Skaihub is committed to fostering the next generation of tech innovators. We are excited to launch our scholarship program, which will provide financial assistance and mentorship opportunities to talented individuals pursuing careers in software development and computer science.',
      creator: 'By Skaihub | November 1, 2024  |',
      views: 50,
      stars: 4,
      description: '',
    },
    {
      id: 7,
      image: require('../assets/bg6.jpg'),
      title: 'OUR WIVES HAVE GONE MAD',
      content: 'Skaihub is committed to fostering the next generation of tech innovators. We are excited to launch our scholarship program, which will provide financial assistance and mentorship opportunities to talented individuals pursuing careers in software development and computer science.',
      creator: 'By Skaihub | November 20, 2024  |',
      views: 50,
      stars: 4,
      description: '',
    },
    {
      id: 8,
      image: require('../assets/bg5.jpg'),
      title: 'ADIZA THE MAD WOMAN 8',
      content: 'Skaihub is committed to fostering the next generation of tech innovators. We are excited to launch our scholarship program, which will provide financial assistance and mentorship opportunities to talented individuals pursuing careers in software development and computer science.',
      creator: 'By Skaihub | November 1, 2024  |',
      views: 50,
      stars: 4,
      description: '',
    },
    {
      id: 9,
      image: require('../assets/bg5.jpg'),
      title: 'ADIZA THE MAD WOMAN 9',
      content: 'Skaihub is committed to fostering the next generation of tech innovators. We are excited to launch our scholarship program, which will provide financial assistance and mentorship opportunities to talented individuals pursuing careers in software development and computer science.',
      creator: 'By Skaihub | November 1, 2024  |',
      views: 50,
      stars: 4,
      description: '',
    },
  ];
  
  export default EventData;
  